from .. import db

class BattingInfo(db.Model):
    __tablename__ = "batting_info"

    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey("player_bio.player_id"), nullable=False)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    game_date = db.Column(db.Date, nullable=True)
    game_bam_id = db.Column(db.Integer)
    at_bat_number = db.Column(db.Integer)
    inning = db.Column(db.Integer)
    pitch_seq = db.Column(db.Integer)
    event_type = db.Column(db.String(100))
    description = db.Column(db.Text)
    hit_trajectory = db.Column(db.String(50))
    hit_exit_speed = db.Column(db.Float)
    hit_vertical_angle = db.Column(db.Float)
    hit_horizontal_angle = db.Column(db.Float)
    hit_distance = db.Column(db.Float)
    hit_bearing = db.Column(db.Float)
    pre_balls = db.Column(db.Integer)
    pre_strikes = db.Column(db.Integer)
    post_balls = db.Column(db.Integer)
    post_strikes = db.Column(db.Integer)
    pre_vscore = db.Column(db.Integer)
    post_vscore = db.Column(db.Integer)
    pre_basecode = db.Column(db.Integer)
    post_basecode = db.Column(db.Integer)
    pre_r1_bam_id = db.Column(db.Integer)
    pre_r2_bam_id = db.Column(db.Integer)
    pre_r3_bam_id = db.Column(db.Integer)
    post_r1_bam_id = db.Column(db.Integer)
    post_r2_bam_id = db.Column(db.Integer)
    post_r3_bam_id = db.Column(db.Integer)
    swing = db.Column(db.Boolean)
    contact = db.Column(db.Boolean)
    in_play = db.Column(db.Boolean)
    pitch_type = db.Column(db.String(50)) 
    plate_x = db.Column(db.Float)         
    plate_z = db.Column(db.Float)
    called_strike = db.Column(db.Boolean)
    swinging_strike = db.Column(db.Boolean)
    chase = db.Column(db.Boolean)
    ball = db.Column(db.Boolean)