from .. import db

class PitchingInfo(db.Model):
    __tablename__ = "pitching_info"

    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, db.ForeignKey("player_bio.player_id"), nullable=False)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    game_date = db.Column(db.Date, nullable=True)
    game_bam_id = db.Column(db.Integer)
    at_bat_number = db.Column(db.Integer)
    inning = db.Column(db.Integer)
    pitch_seq = db.Column(db.Integer)
    pitch_type = db.Column(db.String(50))
    horz_break = db.Column(db.Float)
    induced_vert_break = db.Column(db.Float)
    rel_speed = db.Column(db.Float)
    pre_outs = db.Column(db.Integer)
    post_outs = db.Column(db.Integer)
    pre_vscore = db.Column(db.Integer)
    post_vscore = db.Column(db.Integer)
    pre_balls = db.Column(db.Integer)
    pre_strikes = db.Column(db.Integer)
    post_balls = db.Column(db.Integer)
    post_strikes = db.Column(db.Integer)
    event_type = db.Column(db.String(100))
    description = db.Column(db.Text)
    spin_rate = db.Column(db.Float)
    spin_axis = db.Column(db.Float)
    zone_speed = db.Column(db.Float)
    plate_x = db.Column(db.Float)
    plate_z = db.Column(db.Float)
    extension = db.Column(db.Float)
    tilt = db.Column(db.String(50))
    hit_exit_speed = db.Column(db.Float)
    hit_distance = db.Column(db.Float)
    hit_vertical_angle = db.Column(db.Float)
    hit_horizontal_angle = db.Column(db.Float)
    in_play = db.Column(db.Boolean)
    hit_trajectory = db.Column(db.String(50))